version: '3.2'
services:
  my_search_db:
    container_name: my_search_db
    image: 'postgres:11.1'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
  my_search_elasticsearch:
    container_name: my_search_elasticsearch
    image: 'elasticsearch:7.3.1'
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
  my_search_backend:
    container_name: my_search_backend
    depends_on:
      - my_search_db
      - my_search_elasticsearch
    build:
      context: ../..
      dockerfile: 'deploy/docker_local_dev/backend/Dockerfile'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - BASE_URL=${BASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    ports:
      - '8000:8000'
    volumes:
      - ../../backend:/app
    command: python /app/manage.py runserver 0:8000